// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://loiyarovjrqtcxdgreny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvaXlhcm92anJxdGN4ZGdyZW55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3MjU0OTMsImV4cCI6MjA4NjMwMTQ5M30.NGc1L-222k9CK0uOCZdSKtgr-GlAKDYzcb8iRsTJ9cM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});